package com.example.serviceapp.data.repository

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateListOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import com.example.serviceapp.data.model.Job
import com.example.serviceapp.data.model.Provider
import com.example.serviceapp.data.model.ServiceHistory
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.firestore.FieldValue
import com.google.firebase.firestore.FirebaseFirestore
import com.google.firebase.firestore.ListenerRegistration
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job as CoroutineJob
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.tasks.await
import java.util.UUID

object FakeRepository {

    var provider       by mutableStateOf<Provider?>(null)
    val jobs            = mutableStateListOf<Job>()
    var totalGenerated by mutableStateOf(0)
    var intervalMs     by mutableStateOf(15000L)
    var fastMode       by mutableStateOf(false)
    var loggedIn       by mutableStateOf(false)

    private val auth: FirebaseAuth      get() = FirebaseAuth.getInstance()
    private val db:   FirebaseFirestore get() = FirebaseFirestore.getInstance()
    private var loopJob: CoroutineJob?  = null

    val serviceTypes = listOf(
        "এসি রিপেয়ার", "প্লাম্বিং", "ইলেকট্রিক কাজ",
        "ডিপ ক্লিনিং", "রং করা", "কাঠের কাজ",
        "যন্ত্রপাতি মেরামত", "পোকামাকড় নিয়ন্ত্রণ"
    )

    private val areas = listOf(
        "মিরপুর ১", "মিরপুর ১০", "মিরপুর ১২", "ধানমন্ডি",
        "গুলশান ১", "গুলশান ২", "বনানী", "উত্তরা", "মোহাম্মদপুর", "রামপুরা"
    )

    private val problemOverviews = mapOf(
        "এসি রিপেয়ার" to listOf(
            "এসি চালু থাকলেও ঠান্ডা হচ্ছে না। আউটডোর কম্প্রেসার ঠিক আছে কিন্তু ইনডোর থেকে গরম বাতাস বেরোচ্ছে।",
            "গতকাল সন্ধ্যা থেকে আউটডোর ইউনিট থেকে অস্বাভাবিক শব্দ হচ্ছে। কম্পন বাড়ছে।",
            "ইনডোর ইউনিট থেকে মেঝেতে পানি পড়ছে। ড্রেন লাইন বন্ধ হয়ে থাকতে পারে।",
            "এসি চালু হওয়ার ১০ মিনিট পরেই বন্ধ হয়ে যাচ্ছে।"
        ),
        "প্লাম্বিং" to listOf(
            "রান্নাঘরের সিঙ্কের ড্রেন পুরোপুরি বন্ধ। পানি জমে আছে, নামছে না।",
            "বাথরুমের ট্যাপ সম্পূর্ণ বন্ধ করলেও পানি পড়ছে।",
            "সকাল থেকে সব ট্যাপে পানির চাপ খুব কম। শাওয়ার প্রায় কাজ করছে না।",
            "টয়লেটের ফ্লাশ ঠিকমতো কাজ করছে না।"
        ),
        "ইলেকট্রিক কাজ" to listOf(
            "প্রতি ঘণ্টায় মেইন সার্কিট ব্রেকার পড়ে যাচ্ছে।",
            "দুটি পাওয়ার সকেটে প্লাগ লাগালে স্ফুলিঙ্গ দেখা যাচ্ছে।",
            "সিলিং ফ্যানের স্পিড কন্ট্রোল কাজ করছে না।",
            "মাস্টার বেডরুমে লাইট জ্বলছে-নিভছে।"
        ),
        "ডিপ ক্লিনিং" to listOf(
            "নতুন ভাড়াটে আসার আগে পুরো ফ্ল্যাট ডিপ ক্লিন দরকার।",
            "রান্নাঘরের এক্সজস্ট ফ্যান ও দেয়ালে মোটা তেলের আস্তর জমেছে।",
            "বাথরুমের টাইলসে গাঢ় ছাতা ও ময়লা জমেছে।",
            "নির্মাণ কাজের পর পরিষ্কার দরকার।"
        ),
        "রং করা" to listOf(
            "২টি বেডরুমের দেয়ালের রং উঠে যাচ্ছে। স্যান্ডিং করে নতুন কোট দরকার।",
            "বাইরের সীমানা প্রাচীরে বড় ফাটল ও রং বিবর্ণ হয়ে গেছে।",
            "লিভিং রুমের একটি দেয়াল নতুন রং করতে হবে।",
            "ছাদ থেকে পানি চুঁয়ে ডাইনিং রুমের ছাদে দাগ পড়েছে।"
        ),
        "কাঠের কাজ" to listOf(
            "মাস্টার বেডরুমের দরজার কব্জা ভাঙা।",
            "রান্নাঘরের ক্যাবিনেটের তাক বাসনের ভারে বেঁকে গেছে।",
            "তিনটি কাঠের মেঝের পাটাতন জোরে শব্দ করছে।",
            "জানালার ফ্রেম পানিতে পচে গেছে।"
        ),
        "যন্ত্রপাতি মেরামত" to listOf(
            "ওয়াশিং মেশিন স্পিন সাইকেলে তীব্র শব্দ করছে।",
            "ফ্রিজ ঠান্ডা রাখতে পারছে না। খাবার নষ্ট হয়ে যাচ্ছে।",
            "মাইক্রোওয়েভ চালু করলে ভেতরে স্ফুলিঙ্গ দেখা যাচ্ছে।",
            "ডিশওয়াশার থেকে পানি বের হচ্ছে।"
        ),
        "পোকামাকড় নিয়ন্ত্রণ" to listOf(
            "রান্নাঘরে দিনের বেলায়ও তেলাপোকা দেখা যাচ্ছে।",
            "কাঠের বুকশেলফ ও দরজার ফ্রেমে উইপোকার ক্ষতি পাওয়া গেছে।",
            "খাবার রাখার জায়গার কাছে ইঁদুর দেখা গেছে।",
            "ছাদে জমে থাকা পানিতে মশার বংশ বিস্তার হচ্ছে।"
        )
    )

    // ── Register ─────────────────────────────────────────────────────────────
    suspend fun register(
        name: String, phone: String, email: String, password: String,
        nid: String, photo: String, baseFee: Double,
        serviceType: String, certificate: String
    ): Result<Unit> = runCatching {
        val result = auth.createUserWithEmailAndPassword(email.trim(), password).await()
        val uid    = result.user?.uid ?: error("No user ID returned")

        val data = hashMapOf<String, Any?>(
            "name"         to name.trim(),
            "phone"        to phone.trim(),
            "email"        to email.trim(),
            "nid"          to nid.trim(),
            "serviceType"  to serviceType,
            "baseFee"      to baseFee,
            "photo"        to "",
            "certificate"  to "",
            "availability" to "available",
            "rating"       to 4.5,
            "isApproved"   to null,
            "createdAt"    to FieldValue.serverTimestamp()
        )
        db.collection("providers").document(uid).set(data).await()

        provider = Provider(
            id = uid, name = name.trim(), phone = phone.trim(),
            email = email.trim(), photo = photo,
            nid = nid.trim(), baseFee = baseFee,
            serviceType = serviceType, certificate = certificate,
            isApproved = null  // pending until admin approves
        )
        loggedIn = true
        // Do NOT start loop — wait for approval
    }

    // ── Login ─────────────────────────────────────────────────────────────────
    suspend fun login(email: String, password: String): Result<Unit> = runCatching {
        val result = auth.signInWithEmailAndPassword(email.trim(), password).await()
        val uid    = result.user?.uid ?: error("No user ID returned")
        loadProviderFromFirestore(uid)
        loggedIn = true
        if (provider?.isApproved == true) startLoop()
    }

    // ── Auto-restore session on app start ────────────────────────────────────
    suspend fun loadCurrentUser(): Boolean {
        val uid = auth.currentUser?.uid ?: return false
        return runCatching {
            loadProviderFromFirestore(uid)
            loggedIn = true
            if (provider?.isApproved == true) startLoop()
        }.isSuccess
    }

    private suspend fun loadProviderFromFirestore(uid: String) {
        val doc = db.collection("providers").document(uid).get().await()
        val approvedRaw = doc.get("isApproved")
        provider = Provider(
            id           = uid,
            name         = doc.getString("name")         ?: "",
            phone        = doc.getString("phone")        ?: "",
            email        = doc.getString("email")        ?: "",
            photo        = doc.getString("photo")        ?: "",
            nid          = doc.getString("nid")          ?: "",
            baseFee      = doc.getDouble("baseFee")      ?: 300.0,
            serviceType  = doc.getString("serviceType")  ?: "",
            certificate  = doc.getString("certificate")  ?: "",
            availability = doc.getString("availability") ?: "available",
            rating       = doc.getDouble("rating")       ?: 4.5,
            isApproved   = if (approvedRaw == null) null else approvedRaw as? Boolean
        )
    }

    // Real-time listener — auto fires when admin approves/rejects
    fun listenForApproval(
        onApproved: () -> Unit,
        onRejected: () -> Unit
    ): ListenerRegistration? {
        val uid = auth.currentUser?.uid ?: return null
        return db.collection("providers").document(uid).addSnapshotListener { snap, _ ->
            val raw = snap?.get("isApproved")
            when {
                raw == true  -> { provider?.isApproved = true;  startLoop(); onApproved() }
                raw == false -> { provider?.isApproved = false; onRejected() }
            }
        }
    }

    // ── Logout ────────────────────────────────────────────────────────────────
    fun logout() {
        auth.signOut()
        loopJob?.cancel()
        loopJob        = null
        loggedIn       = false
        provider       = null
        totalGenerated = 0
        jobs.clear()
    }

    fun setAvailability(status: String) { provider?.availability = status }

    fun clearHistory() {
        provider?.let { p ->
            p.history.clear()
            p.advance = 0.0
        }
    }

    // ── Job simulation ────────────────────────────────────────────────────────
    private fun startLoop() {
        loopJob?.cancel()
        loopJob = CoroutineScope(Dispatchers.Main).launch {
            while (true) { delay(intervalMs); spawnJob() }
        }
    }

    fun spawnJob() {
        totalGenerated++
        val type     = provider?.serviceType?.takeIf { it.isNotBlank() } ?: serviceTypes.random()
        val overview = problemOverviews[type]?.random() ?: "সেবা প্রয়োজন।"
        jobs.add(Job(
            id          = UUID.randomUUID().toString(),
            description = "$type #$totalGenerated",
            address     = areas.random(),
            phone       = "01${(500000000..999999999).random()}",
            overview    = overview
        ))
        if (jobs.size > 6) jobs.removeFirst()
    }

    fun applySpeed(fast: Boolean) {
        fastMode   = fast
        intervalMs = if (fast) 4000L else 15000L
    }

    fun accept(job: Job) {
        val idx = jobs.indexOfFirst { it.id == job.id }
        if (idx >= 0) {
            jobs[idx] = job.copy(status = "done")
            provider?.let { p ->
                p.advance += p.baseFee
                p.history.add(ServiceHistory(job.id, job.description, p.baseFee))
            }
        }
    }
}
