package com.example.serviceapp.data.repository

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateListOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import com.example.serviceapp.data.model.Job
import com.example.serviceapp.data.model.Provider
import com.example.serviceapp.data.model.ServiceHistory
import com.example.serviceapp.utils.AppStrings
import com.example.serviceapp.utils.ServiceData
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.firestore.FieldValue
import com.google.firebase.firestore.FirebaseFirestore
import com.google.firebase.firestore.ListenerRegistration
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job as CoroutineJob
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.tasks.await
import java.util.UUID

object FakeRepository {

    var provider       by mutableStateOf<Provider?>(null)
    val jobs            = mutableStateListOf<Job>()
    var totalGenerated by mutableStateOf(0)
    var intervalMs     by mutableStateOf(15000L)
    var fastMode       by mutableStateOf(false)
    var loggedIn       by mutableStateOf(false)

    private val auth: FirebaseAuth      get() = FirebaseAuth.getInstance()
    private val db:   FirebaseFirestore get() = FirebaseFirestore.getInstance()
    private var loopJob: CoroutineJob?  = null

    // Service type IDs — match ServiceData.categories
    val serviceTypes get() = ServiceData.categories.map { it.id }

    private val areas = listOf(
        "মিরপুর ১", "মিরপুর ১০", "মিরপুর ১২", "ধানমন্ডি",
        "গুলশান ১", "গুলশান ২", "বনানী", "উত্তরা", "মোহাম্মদপুর", "রামপুরা"
    )

    // Problem overviews derived from ServiceData — keyed by category ID
    private val problemOverviews: Map<String, List<String>> get() =
        ServiceData.categories.associate { cat ->
            cat.id to cat.problems
                .filter { !it.isWarning }  // skip warning items for auto-generation
                .map { it.bnLabel }
        }

    // ── Register ─────────────────────────────────────────────────────────────
    suspend fun register(
        name: String, phone: String, email: String, password: String,
        nid: String, photo: String, baseFee: Double,
        serviceType: String, certificate: String
    ): Result<Unit> = runCatching {
        val result = auth.createUserWithEmailAndPassword(email.trim(), password).await()
        val uid    = result.user?.uid ?: error("No user ID returned")

        val data = hashMapOf<String, Any?>(
            "name"         to name.trim(),
            "phone"        to phone.trim(),
            "email"        to email.trim(),
            "nid"          to nid.trim(),
            "serviceType"  to serviceType,
            "baseFee"      to baseFee,
            "photo"        to "",
            "certificate"  to "",
            "availability" to "available",
            "rating"       to 4.5,
            "isApproved"   to null,
            "createdAt"    to FieldValue.serverTimestamp()
        )
        db.collection("providers").document(uid).set(data).await()

        provider = Provider(
            id = uid, name = name.trim(), phone = phone.trim(),
            email = email.trim(), photo = photo,
            nid = nid.trim(), baseFee = baseFee,
            serviceType = serviceType, certificate = certificate,
            isApproved = null  // pending until admin approves
        )
        loggedIn = true
        // Do NOT start loop — wait for approval
    }

    // ── Login ─────────────────────────────────────────────────────────────────
    suspend fun login(email: String, password: String): Result<Unit> = runCatching {
        val result = auth.signInWithEmailAndPassword(email.trim(), password).await()
        val uid    = result.user?.uid ?: error("No user ID returned")
        loadProviderFromFirestore(uid)
        loggedIn = true
        if (provider?.isApproved == true) startLoop()
    }

    // ── Auto-restore session on app start ────────────────────────────────────
    suspend fun loadCurrentUser(): Boolean {
        val uid = auth.currentUser?.uid ?: return false
        return runCatching {
            loadProviderFromFirestore(uid)
            loggedIn = true
            if (provider?.isApproved == true) startLoop()
        }.isSuccess
    }

    private suspend fun loadProviderFromFirestore(uid: String) {
        val doc = db.collection("providers").document(uid).get().await()
        val approvedRaw = doc.get("isApproved")
        provider = Provider(
            id           = uid,
            name         = doc.getString("name")         ?: "",
            phone        = doc.getString("phone")        ?: "",
            email        = doc.getString("email")        ?: "",
            photo        = doc.getString("photo")        ?: "",
            nid          = doc.getString("nid")          ?: "",
            baseFee      = doc.getDouble("baseFee")      ?: 300.0,
            serviceType  = doc.getString("serviceType")  ?: "",
            certificate  = doc.getString("certificate")  ?: "",
            availability = doc.getString("availability") ?: "available",
            rating       = doc.getDouble("rating")       ?: 4.5,
            isApproved   = if (approvedRaw == null) null else approvedRaw as? Boolean
        )
    }

    // Real-time listener — auto fires when admin approves/rejects
    fun listenForApproval(
        onApproved: () -> Unit,
        onRejected: () -> Unit
    ): ListenerRegistration? {
        val uid = auth.currentUser?.uid ?: return null
        return db.collection("providers").document(uid).addSnapshotListener { snap, _ ->
            val raw = snap?.get("isApproved")
            when {
                raw == true  -> { provider?.isApproved = true;  startLoop(); onApproved() }
                raw == false -> { provider?.isApproved = false; onRejected() }
            }
        }
    }

    // ── Logout ────────────────────────────────────────────────────────────────
    fun logout() {
        auth.signOut()
        loopJob?.cancel()
        loopJob        = null
        loggedIn       = false
        provider       = null
        totalGenerated = 0
        jobs.clear()
    }

    fun setAvailability(status: String) { provider?.availability = status }

    fun clearHistory() {
        provider?.let { p ->
            p.history.clear()
            p.advance = 0.0
        }
    }

    // ── Job simulation ────────────────────────────────────────────────────────
    private fun startLoop() {
        loopJob?.cancel()
        loopJob = CoroutineScope(Dispatchers.Main).launch {
            while (true) { delay(intervalMs); spawnJob() }
        }
    }

    fun spawnJob() {
        totalGenerated++
        val typeId   = provider?.serviceType?.takeIf { it.isNotBlank() } ?: serviceTypes.random()
        val typeName = AppStrings.serviceTypeName(typeId)
        val overview = problemOverviews[typeId]?.randomOrNull() ?: "সেবা প্রয়োজন।"
        jobs.add(Job(
            id          = UUID.randomUUID().toString(),
            description = "$typeName #$totalGenerated",
            address     = areas.random(),
            phone       = "01${(500000000..999999999).random()}",
            overview    = overview
        ))
        if (jobs.size > 6) jobs.removeFirst()
    }

    fun applySpeed(fast: Boolean) {
        fastMode   = fast
        intervalMs = if (fast) 4000L else 15000L
    }

    fun accept(job: Job) {
        val idx = jobs.indexOfFirst { it.id == job.id }
        if (idx >= 0) {
            jobs[idx] = job.copy(status = "done")
            provider?.let { p ->
                p.advance += p.baseFee
                p.history.add(ServiceHistory(job.id, job.description, p.baseFee))
            }
        }
    }
}
